version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: oficina_mecanica_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oficina_mecanica
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - oficina_network

  # Opcional: PgAdmin para gerenciar o banco visualmente
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: oficina_mecanica_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@oficina.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - oficina_network

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  oficina_network:
    driver: bridge
