services:
  postgres:
    image: postgres:16-alpine
    container_name: oficina_mecanica_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oficina_mecanica
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - oficina_network

  mailpit:
    image: axllent/mailpit:latest
    container_name: oficina_mecanica_mailpit
    restart: always
    ports:
      - "8025:8025" # UI web
      - "1025:1025" # SMTP
    networks:
      - oficina_network

  api:
    build:
      context: .
      dockerfile: OficinaMecanica.API/Dockerfile
    container_name: oficina_mecanica_api
    restart: always
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=oficina_mecanica;Username=postgres;Password=postgres"
      Jwt__SecretKey: "OficinaMecanica@SecretKey#2024!MustBe32CharsMin"
      Jwt__Issuer: "OficinaMecanicaAPI"
      Jwt__Audience: "OficinaMecanicaClients"
      Jwt__ExpiracaoHoras: "24"
      Email__Host: "mailpit"
      Email__Port: "1025"
      Email__RemetenteEmail: "naoresponda@oficinamecanica.com.br"
      Email__RemetenteNome: "Oficina Mecânica"
    depends_on:
      postgres:
        condition: service_healthy
      mailpit:
        condition: service_started
    networks:
      - oficina_network

volumes:
  postgres_data:
    driver: local

networks:
  oficina_network:
    driver: bridge
