sonar.projectKey=oficina-mecanica
sonar.projectName=Oficina Mecanica API
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/Migrations/**,**/obj/**,**/bin/**

sonar.cs.opencover.reportsPaths=TestResults/coverage/**/coverage.opencover.xml

sonar.language=cs
sonar.sourceEncoding=UTF-8
