// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OficinaMecanica.Infrastructure.Persistence;

#nullable disable

namespace OficinaMecanica.Infrastructure.Migrations
{
    [DbContext(typeof(OficinaMecanicaDbContext))]
    [Migration("20260403194021_ChangeStatusToString")]
    partial class ChangeStatusToString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OficinaMecanica.Domain.Entities.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("number");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_work_orders");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_work_orders_created_at");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_work_orders_customer_id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_work_orders_number");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_work_orders_status");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_work_orders_vehicle_id");

                    b.ToTable("work_orders", (string)null);
                });

            modelBuilder.Entity("OficinaMecanica.Domain.Entities.WorkOrder", b =>
                {
                    b.OwnsMany("OficinaMecanica.Domain.ValueObjects.PartItem", "Parts", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("code");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("description");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer")
                                .HasColumnName("quantity");

                            b1.Property<decimal>("UnitPrice")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("unit_price");

                            b1.Property<Guid>("work_order_id")
                                .HasColumnType("uuid")
                                .HasColumnName("work_order_id");

                            b1.HasKey("id")
                                .HasName("pk_work_order_parts");

                            b1.HasIndex("Code")
                                .HasDatabaseName("ix_work_order_parts_code");

                            b1.HasIndex("work_order_id")
                                .HasDatabaseName("ix_work_order_parts_work_order_id");

                            b1.ToTable("work_order_parts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("work_order_id")
                                .HasConstraintName("fk_work_order_parts_work_orders");
                        });

                    b.OwnsMany("OficinaMecanica.Domain.ValueObjects.ServiceItem", "Services", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("description");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer")
                                .HasColumnName("quantity");

                            b1.Property<decimal>("UnitPrice")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("unit_price");

                            b1.Property<Guid>("work_order_id")
                                .HasColumnType("uuid")
                                .HasColumnName("work_order_id");

                            b1.HasKey("id")
                                .HasName("pk_work_order_services");

                            b1.HasIndex("work_order_id")
                                .HasDatabaseName("ix_work_order_services_work_order_id");

                            b1.ToTable("work_order_services", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("work_order_id")
                                .HasConstraintName("fk_work_order_services_work_orders");
                        });

                    b.Navigation("Parts");

                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
