// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OficinaMecanica.Infrastructure.Persistence;

#nullable disable

namespace OficinaMecanica.Infrastructure.Migrations
{
    [DbContext(typeof(OficinaMecanicaDbContext))]
    partial class OficinaMecanicaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OficinaMecanica.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.HasIndex("Documento")
                        .IsUnique()
                        .HasDatabaseName("ix_clientes_documento");

                    b.ToTable("clientes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567801"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Documento = "74185296355",
                            Email = "joao@email.com",
                            Nome = "Joao da Silva",
                            Telefone = "51999990001"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567802"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Documento = "85296374100",
                            Email = "maria@email.com",
                            Nome = "Maria Oliveira",
                            Telefone = "51999990002"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567803"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Documento = "96374185200",
                            Email = "carlos@email.com",
                            Nome = "Carlos Pereira",
                            Telefone = "51999990003"
                        });
                });

            modelBuilder.Entity("OficinaMecanica.Domain.Entities.OrdemServico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EntregueEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entregue_em");

                    b.Property<DateTime?>("FinalizadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalizada_em");

                    b.Property<DateTime?>("IniciadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("iniciada_em");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("observacoes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VeiculoId")
                        .HasColumnType("uuid")
                        .HasColumnName("veiculo_id");

                    b.HasKey("Id")
                        .HasName("pk_ordens_servico");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_ordens_servico_cliente_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_ordens_servico_criada_em");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_ordens_servico_numero");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_ordens_servico_status");

                    b.HasIndex("VeiculoId")
                        .HasDatabaseName("ix_ordens_servico_veiculo_id");

                    b.ToTable("ordens_servico", (string)null);
                });

            modelBuilder.Entity("OficinaMecanica.Domain.Entities.Peca", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("preco_unitario");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_estoque");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_pecas");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_pecas_codigo");

                    b.ToTable("pecas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-0123-defa-234567890001"),
                            Codigo = "OL-5W30",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Oleo Motor 5W30 1L",
                            PrecoUnitario = 35.90m,
                            QuantidadeEstoque = 50
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-0123-defa-234567890002"),
                            Codigo = "FO-001",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Filtro de Oleo Universal",
                            PrecoUnitario = 22.50m,
                            QuantidadeEstoque = 30
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-0123-defa-234567890003"),
                            Codigo = "PF-002",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Pastilha de Freio Dianteira",
                            PrecoUnitario = 89.90m,
                            QuantidadeEstoque = 20
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-0123-defa-234567890004"),
                            Codigo = "FA-003",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Filtro de Ar Universal",
                            PrecoUnitario = 28.00m,
                            QuantidadeEstoque = 25
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-0123-defa-234567890005"),
                            Codigo = "VI-004",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Vela de Ignicao (unidade)",
                            PrecoUnitario = 18.00m,
                            QuantidadeEstoque = 40
                        });
                });

            modelBuilder.Entity("OficinaMecanica.Domain.Entities.Servico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("preco");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_servicos");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_servicos_nome");

                    b.ToTable("servicos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789001"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Troca do oleo do motor com filtro",
                            Nome = "Troca de Oleo",
                            Preco = 120.00m
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789002"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Alinhamento das rodas dianteiras e traseiras",
                            Nome = "Alinhamento",
                            Preco = 90.00m
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789003"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Balanceamento de todas as rodas",
                            Nome = "Balanceamento",
                            Preco = 80.00m
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789004"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Inspecao e ajuste do sistema de freios",
                            Nome = "Revisao de Freios",
                            Preco = 150.00m
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789005"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Revisao completa: fluidos, filtros e correia",
                            Nome = "Revisao Geral",
                            Preco = 350.00m
                        });
                });

            modelBuilder.Entity("OficinaMecanica.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("perfil");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("senha_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("OficinaMecanica.Domain.Entities.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modelo");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("placa");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_veiculos");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_veiculos_cliente_id");

                    b.HasIndex("Placa")
                        .IsUnique()
                        .HasDatabaseName("ix_veiculos_placa");

                    b.ToTable("veiculos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            Ano = 2018,
                            ClienteId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567801"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Marca = "Volkswagen",
                            Modelo = "Gol",
                            Placa = "SED0001"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678902"),
                            Ano = 2021,
                            ClienteId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567802"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Marca = "Hyundai",
                            Modelo = "HB20",
                            Placa = "SED0002"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678903"),
                            Ano = 2023,
                            ClienteId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567803"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Marca = "Toyota",
                            Modelo = "Corolla",
                            Placa = "SED0003"
                        });
                });

            modelBuilder.Entity("OficinaMecanica.Domain.Entities.OrdemServico", b =>
                {
                    b.OwnsMany("OficinaMecanica.Domain.ValueObjects.ItemPeca", "Pecas", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<string>("Codigo")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("codigo");

                            b1.Property<string>("Descricao")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("descricao");

                            b1.Property<Guid>("PecaId")
                                .HasColumnType("uuid")
                                .HasColumnName("peca_id");

                            b1.Property<decimal>("PrecoUnitario")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("preco_unitario");

                            b1.Property<int>("Quantidade")
                                .HasColumnType("integer")
                                .HasColumnName("quantidade");

                            b1.Property<Guid>("ordem_servico_id")
                                .HasColumnType("uuid")
                                .HasColumnName("ordem_servico_id");

                            b1.HasKey("id")
                                .HasName("pk_ordem_servico_pecas");

                            b1.HasIndex("Codigo")
                                .HasDatabaseName("ix_ordem_servico_pecas_codigo");

                            b1.HasIndex("ordem_servico_id")
                                .HasDatabaseName("ix_ordem_servico_pecas_ordem_servico_id");

                            b1.ToTable("ordem_servico_pecas", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ordem_servico_id")
                                .HasConstraintName("fk_ordem_servico_pecas_ordens_servico");
                        });

                    b.OwnsMany("OficinaMecanica.Domain.ValueObjects.ItemServico", "Servicos", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<string>("Descricao")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("descricao");

                            b1.Property<DateTime?>("FinalizadoEm")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("finalizado_em");

                            b1.Property<DateTime?>("IniciadoEm")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("iniciado_em");

                            b1.Property<decimal>("PrecoUnitario")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("preco_unitario");

                            b1.Property<int>("Quantidade")
                                .HasColumnType("integer")
                                .HasColumnName("quantidade");

                            b1.Property<Guid>("ServicoId")
                                .HasColumnType("uuid")
                                .HasColumnName("servico_id");

                            b1.Property<Guid>("ordem_servico_id")
                                .HasColumnType("uuid")
                                .HasColumnName("ordem_servico_id");

                            b1.HasKey("id")
                                .HasName("pk_ordem_servico_servicos");

                            b1.HasIndex("ordem_servico_id")
                                .HasDatabaseName("ix_ordem_servico_servicos_ordem_servico_id");

                            b1.ToTable("ordem_servico_servicos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ordem_servico_id")
                                .HasConstraintName("fk_ordem_servico_servicos_ordens_servico");
                        });

                    b.Navigation("Pecas");

                    b.Navigation("Servicos");
                });

            modelBuilder.Entity("OficinaMecanica.Domain.Entities.Veiculo", b =>
                {
                    b.HasOne("OficinaMecanica.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_veiculos_clientes");

                    b.Navigation("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
