name: SonarQube

on:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Install Coverage Tool
        run: dotnet tool install --global dotnet-coverage

      - name: Sonar Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin /k:"konrath9_OficinaMecanica" /o:"konrath9" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.vscoveragexml.reportsPaths="coverage.xml" /d:sonar.exclusions="**/Migrations/**" /d:sonar.projectBaseDir="${{ github.workspace }}"
          dotnet build
          dotnet-coverage collect "dotnet test" -f xml -o coverage.xml
          dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"